---
binaries:
  hadolint:
    version: 2.12.0
    check: hadolint --version
    url: https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-{% if ansible_distribution == "MacOSX" %}Darwin{% else %}Linux{% endif %}-x86_64
    name: hadolint
  jl:
    version: 1.6.0
    check: jl --version
    url: https://github.com/koenbollen/jl/releases/download/v1.6.0/jl_{% if ansible_distribution == "MacOSX" %}darwin{% else %}linux{% endif %}_amd64
    name: jl
  kubectl:
    version: 1.29.3
    check: kubectl version --client=true
    url: https://dl.k8s.io/release/v1.29.3/bin/{% if ansible_distribution == "MacOSX" %}darwin/arm64{% else %}linux/amd64{% endif %}/kubectl
    name: kubectl
  mkcert:
    version: 1.4.4
    check: mkcert -version
    url: https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-{% if ansible_distribution == "MacOSX" %}darwin-arm64{% else %}linux-amd64{% endif %}
    name: mkcert
  shfmt:
    version: 3.8.0
    check: shfmt --version
    url: https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_{% if ansible_distribution == "MacOSX" %}darwin_arm64{% else %}linux_amd64{% endif %}
    name: shfmt
  mc:
    version: RELEASE.2024-03-30T15-29-52Z
    check: mc --version
    url: https://dl.min.io/client/mc/release/{% if ansible_distribution == "MacOSX" %}darwin-arm64{% else %}linux-amd64{% endif %}/mc.RELEASE.2024-03-30T15-29-52Z
    name: mc

archived_binaries:
  terraform:
    version: 1.7.5
    check: terraform version
    url: https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_{% if ansible_distribution == "MacOSX" %}darwin_arm64{% else %}linux_amd64{% endif %}.zip
  packer:
    version: 1.10.2
    check: packer --version
    url: https://releases.hashicorp.com/packer/1.10.2/packer_1.10.2_{% if ansible_distribution == "MacOSX" %}darwin_arm64{% else %}linux_amd64{% endif %}.zip
  dive:
    version: 0.12.0
    check: dive --version
    url: https://github.com/wagoodman/dive/releases/download/v0.12.0/dive_0.12.0_{% if ansible_distribution == "MacOSX" %}darwin_arm64{% else %}linux_amd64{% endif %}.tar.gz
  tflint:
    version: 0.50.3
    check: tflint --version
    url: https://github.com/terraform-linters/tflint/releases/download/v0.50.3/tflint_{% if ansible_distribution == "MacOSX" %}darwin_arm64{% else %}linux_amd64{% endif %}.zip
  starship:
    version: 1.18.2
    check: starship --version
    url: https://github.com/starship/starship/releases/download/v1.18.2/starship-{% if ansible_distribution == "MacOSX" %}aarch64-apple-darwin{% else %}x86_64-unknown-linux-gnu{% endif %}.tar.gz
  kustomize:
    version: 5.4.1
    check: kustomize version
    url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.4.1/kustomize_v5.4.1_{% if ansible_distribution == "MacOSX" %}darwin_arm64{% else %}linux_amd64{% endif %}.tar.gz
  stern:
    version: 1.28.0
    check: stern --version
    url: https://github.com/stern/stern/releases/download/v1.28.0/stern_1.28.0_{% if ansible_distribution == "MacOSX" %}darwin_arm64{% else %}linux_amd64{% endif %}.tar.gz
  helm:
    version: 3.14.3
    check: helm version
    url: https://get.helm.sh/helm-v3.14.3-{% if ansible_distribution == "MacOSX" %}darwin-arm64{% else %}linux-amd64{% endif %}.tar.gz

useful_packages:
  - ack
  - aspell-en
  - aspell-fr
  - bash-completion
  - bind9
  - build-essential
  - ccze
  - cups
  - curl
  - direnv
  - dnsutils
  - evince
  - file-roller
  - filezilla
  - firmware-linux
  - firmware-linux-free
  - firmware-linux-nonfree
  - fonts-hack
  - gdm3
  - gnome-core
  - gnome-shell
  - golang
  - hunspell-fr
  - htop
  - ipcalc
  - iptraf
  - jq
  - keepassxc
  - kitty
  - libnss3-tools
  - libreoffice-calc
  - libreoffice-writer
  - lsb-release
  - lsof
  - nautilus-nextcloud
  - net-tools
  - nethogs
  - netcat-traditional
  - nextcloud-desktop
  - numix-gtk-theme
  - numix-icon-theme
  - podman
  - python3-docker
  - python3-pip
  - rhythmbox
  - rsync
  - shellcheck
  - siege
  - simple-scan
  - strace
  - subversion
  - tcpdump
  - telnet
  - tig
  - traceroute
  - tree
  - vlc
  - wget
  - whois
  - xmlstarlet

vundle_version: "master"

php_packages:
  - php8.2-cli
  - php8.2-xml
composer_path: /usr/local/bin/composer
composer_release: '2.7.2'
composer_global_packages: []

docker_compose_version: v2.4.0

nodejs_version: 20.x
