---

- name: Install everything
  hosts: localhost
  roles:
    - { role: vim, tags: ['vim'] }
    - { role: vundle, tags: ['vundle'] }
    - { role: base16, tags: ['base16'] }
    - { role: utils, tags: ['utils'] }
