---
- name: Create ~/.bashrc
  ansible.builtin.template:
    src: bashrc.j2
    dest: ~/.bashrc
    mode: 0755

- name: Create ~/.bashrc.d directory
  ansible.builtin.file:
    path: ~/.bashrc.d
    state: directory
    mode: 0755

- name: Add golang configuration
  ansible.builtin.template:
    src: golang.j2
    dest: ~/.bashrc.d/golang
    mode: 0755

- name: Add some aliases
  ansible.builtin.template:
    src: aliases.j2
    dest: ~/.bashrc.d/aliases
    mode: 0755
