---
- name: Import utils tasks
  ansible.builtin.import_tasks: utils.yml
  tags: [utils]
- name: Import bash tasks
  ansible.builtin.import_tasks: bash.yml
  tags: [bash]
- name: Import nodejs tasks
  ansible.builtin.import_tasks: nodejs.yml
  tags: [nodejs]
- name: Import vim tasks
  ansible.builtin.import_tasks: vim.yml
  tags: [vim]
- name: Import php tasks
  ansible.builtin.import_tasks: php.yml
  tags: [php]
