---
- name: Add nodejs apt key
  become: true
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /etc/apt/trusted.gpg.d/node.asc
    mode: 0644
    owner: root
    group: root
  when: ansible_distribution != "MacOSX"

- name: Add nodejs repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/node.asc] https://deb.nodesource.com/node_{{ nodejs_version }} nodistro main"
    state: present
    filename: nodejs
    update_cache: true
  when: ansible_distribution != "MacOSX"

- name: Install nodejs package
  become: true
  ansible.builtin.apt:
    name: nodejs
    state: present
  when:
    - ansible_distribution != "MacOSX"
    - '"nodejs" not in ansible_facts.packages'
