---
- name: Add nodejs apt key
  become: true
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  when: ansible_distribution != "MacOSX"

- name: Add nodejs repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    state: present
    filename: nodejs
    update_cache: true
  when: ansible_distribution != "MacOSX"

- name: Install nodejs package
  become: true
  ansible.builtin.apt:
    name: nodejs
    state: present
  when:
    - ansible_distribution != "MacOSX"
    - '"nodejs" not in ansible_facts.packages'
