---
- name: Install php packages
  become: true
  ansible.builtin.apt:
    name: "{{ php_packages }}"

- name: Check if composer binary exists
  ansible.builtin.stat:
    path: "{{ composer_path }}"
  register: composer_bin
  changed_when: false

- name: Check composer version if already installed # noqa 306
  ansible.builtin.shell: |
    "{{ composer_path }}" --version \
    | cut -d " " -f3
  register: composer_version
  changed_when: false
  when: composer_bin is defined

- name: Download Composer if release changed or composer was never installed
  become: true
  ansible.builtin.get_url:
    url: https://getcomposer.org/download/{{ composer_release }}/composer.phar
    dest: /usr/local/bin/composer
    force: true
    owner: root
    group: root
    mode: 0755
  when: (composer_version.stdout.find(composer_release) != 0) or
        (not composer_bin.stat.exists)

- name: Install global composer packages
  community.general.composer:
    global_command: true
    no_dev: true
    command: require
    arguments: "{{ item }}"
  with_items: "{{ composer_global_packages }}"
  when: composer_global_packages is defined and composer_global_packages | length > 0
