---
- name: Configure /etc/apt/preferences
  become: true
  template:
    src: etc/apt/preferences.j2
    dest: /etc/apt/preferences
    mode: 0644
    owner: root
    group: root
  notify:
    - apt update

- name: Configure /etc/apt/sources.list
  become: true
  template:
    src: etc/apt/sources.list.j2
    dest: /etc/apt/sources.list
    mode: 0644
    owner: root
    group: root
  notify:
    - apt update

- name: Remove useless packages
  become: true
  apt:
    name: firefox-esr
    state: absent

- name: Inject packages list in ansible_facts
  package_facts:
    manager: "auto"

- name: Install firefox from unstable repository
  become: true
  apt:
    name: firefox
    state: present
    update_cache: true
    default_release: unstable
  when: '"firefox" not in ansible_facts.packages'

- name: Install useful packages
  become: true
  apt:
    name: "{{ useful_packages }}"
    state: present
    update_cache: true

- name: Configure ~/.config/kitty/kitty.conf
  template:
    src: .config/kitty/kitty.conf.j2
    dest: ~/.config/kitty/kitty.conf
    mode: 0644

- name: Check binaries versions
  shell: >
    set -o pipefail;
    /usr/local/bin/{{ item.value.check }} | head -n 1
  args:
    executable: /usr/bin/bash
  failed_when: false
  changed_when: false
  register: current_binaries_versions
  loop: "{{ binaries | dict2items }}"

- name: Download binaries if needed
  become: true
  get_url:
    url: "{{ item.item.value.url }}"
    dest: "/usr/local/bin/{{ item.item.value.name }}"
    force: true
    mode: 0755
    owner: root
    group: root
  loop: "{{ current_binaries_versions.results }}"
  when: item.stdout is not search(item.item.value.version)

- name: Check archived binaries versions
  shell: >
    set -o pipefail;
    /usr/local/bin/{{ item.value.check }} | head -n 1
  args:
    executable: /usr/bin/bash
  failed_when: false
  changed_when: false
  register: current_archived_binaries_versions
  loop: "{{ archived_binaries | dict2items }}"

- name: Download archived binaries if needed
  become: true
  unarchive:
    src: "{{ item.item.value.url }}"
    dest: /usr/local/bin
    remote_src: true
    mode: 0755
    owner: root
    group: root
  loop: "{{ current_archived_binaries_versions.results }}"
  when: item.stdout is not search(item.item.value.version)

- name: Create starship config
  template:
    src: .config/starship.toml.j2
    dest: ~/.config/starship.toml
    mode: 0644

- name: Install useful gems
  gem:
    name: "{{ item.key }}"
    version: "{{ item.value }}"
    state: present
  with_dict: "{{ gems }}"

- name: Create global git config
  template:
    src: .gitconfig.j2
    dest: ~/.gitconfig
    mode: 0644

- name: Create golang directory
  file:
    path: "~/go"
    state: directory
    mode: 0755

- name: Install evil chrome
  become: true
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  when: '"google-chrome-stable" not in ansible_facts.packages'

- name: Add spotify apt-key
  become: true
  apt_key:
    url: https://download.spotify.com/debian/pubkey_0D811D58.gpg
    state: present

- name: Add spotify repository
  become: true
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    state: present
    filename: spotify
    update_cache: true

- name: Install spotify
  become: true
  apt:
    name: spotify-client
    state: present
    update_cache: true
  when: '"spotify-client" not in ansible_facts.packages'

- name: Add docker apt-key
  become: true
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
    state: present
    filename: docker
    update_cache: true

- name: Install docker
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
  when: '"docker-ce" not in ansible_facts.packages'

- name: Add {{ lookup('env','USER') }} to group docker
  become: true
  user:
    name: "{{ lookup('env','USER') }}"
    groups: docker
    append: true

- name: Download docker-compose autocomplete file
  become: true
  get_url:
    url: "https://raw.githubusercontent.com/docker/compose/{{ binaries.docker_compose.version }}/contrib/completion/bash/docker-compose"
    dest: /etc/bash_completion.d/docker-compose
    mode: 0644
    owner: root
    group: root

- name: Configure ssh client
  template:
    src: .ssh/config.j2
    dest: ~/.ssh/config
    mode: 0600

- name: Create ~/.yamllint.yml configuration file
  template:
    src: .yamllint.yml.j2
    dest: ~/.yamllint.yml
    mode: 0644

- name: Setup splash screen
  become: true
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT=.*"
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"'
  notify:
    - update-grub

- name: Let me use Control+Shift+E please !
  command: gsettings set org.freedesktop.ibus.panel.emoji hotkey "['<Control><Shift>j']"
  changed_when: false

- name: Configure nautilus bookmarks (global)
  become: true
  template:
    src: etc/xdg/user-dirs.defaults.j2
    dest: /etc/xdg/user-dirs.defaults
    mode: 0644
    owner: root
    group: root

- name: Configure nautilus bookmarks (user)
  template:
    src: .config/user-dirs.dirs.j2
    dest: ~/.config/user-dirs.dirs
    mode: 0644

- name: Configure NetworkManager to handle ethernet card
  become: true
  replace:
    path: /etc/NetworkManager/NetworkManager.conf
    regexp: '^\[ifupdown\]\nmanaged=[a-z]*$'
    replace: '[ifupdown]\nmanaged=true'
  notify:
    - NetworkManager restart

- name: Remove default gnome folders
  file:
    path: "~/{{ item }}"
    state: absent
  with_items:
    - Desktop
    - Documents
    - Music
    - Pictures
    - Public
    - Templates
    - Videos

- name: Configure bind9 options
  become: true
  template:
    src: etc/bind/named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: 0644
  notify:
    - restart bind9

- name: Start bind9 at boot
  become: true
  service:
    name: named
    enabled: true
    state: started
