---
- name: Ensure git is installed
  become: true
  package:
    name: "git"
    state: present
  register: git_installed
  until: git_installed is success
  retries: 10
  delay: 2

- name: Create Vim configuration directory
  file:
    path: "~/.vim"
    state: directory

- name: Create Vundle directory
  file:
    path: "~/.vim/bundle"
    state: directory

- name: Clone Vundle repository
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "~/.vim/bundle/Vundle.vim"
    update: true
    force: true
    version: "{{ vundle_version }}"

- name: Install Vundle plugins
  command: 'vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa'
  when: ansible_hostname != 'travis'
