---

binaries:
  docker_compose:
    version: 1.27.4
    check: docker-compose version --short
    url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
    name: docker-compose
  hadolint:
    version: 1.19.0
    check: hadolint --version
    url: https://github.com/hadolint/hadolint/releases/download/v1.19.0/hadolint-Linux-x86_64
    name: hadolint
  jl:
    version: 1.4.0
    check: jl --version
    url: https://github.com/koenbollen/jl/releases/download/v1.4.0/jl_linux_amd64
    name: jl
  stern:
    version: 1.11.0
    check: stern --version
    url: https://github.com/wercker/stern/releases/download/1.11.0/stern_linux_amd64
    name: stern
  kubectl:
    version: 1.19.4
    check: kubectl version --client=true
    url: https://storage.googleapis.com/kubernetes-release/release/v1.19.4/bin/linux/amd64/kubectl
    name: kubectl
  mkcert:
    version: 1.4.3
    check: mkcert -version
    url: https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64
    name: mkcert
  shfmt:
    version: 3.2.1
    check: shfmt --version
    url: https://github.com/mvdan/sh/releases/download/v3.2.1/shfmt_v3.2.1_linux_amd64
    name: shfmt

archived_binaries:
  terraform:
    version: 0.14.2
    check: terraform version
    url: https://releases.hashicorp.com/terraform/0.14.2/terraform_0.14.2_linux_amd64.zip
  packer:
    version: 1.6.5
    check: packer --version
    url: https://releases.hashicorp.com/packer/1.6.5/packer_1.6.5_linux_amd64.zip
  dive:
    version: 0.9.2
    check: dive --version
    url: https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.tar.gz
  tflint:
    version: 0.21.0
    check: tflint --version
    url: https://github.com/terraform-linters/tflint/releases/download/v0.21.0/tflint_linux_amd64.zip
  starship:
    version: 0.47.0
    check: starship --version
    url: https://github.com/starship/starship/releases/download/v0.47.0/starship-x86_64-unknown-linux-gnu.tar.gz
  kustomize:
    version: 3.6.1
    check: kustomize version
    url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.6.1/kustomize_v3.6.1_linux_amd64.tar.gz

gems:
  rake: "13.0.1"
  serverspec: "2.41.5"

google_cloud_sdk_version: "321.0.0-0"

pip_packages:
  - pre-commit==2.9.2
  - docker==4.4.0

useful_packages:
  - ack
  - aspell-en
  - aspell-fr
  - bash-completion
  - build-essential
  - ccze
  - cups
  - curl
  - direnv
  - dnsutils
  - evince
  - file-roller
  - filezilla
  - firmware-linux
  - firmware-linux-free
  - firmware-linux-nonfree
  - gdm3
  - gnome-core
  - gnome-shell
  - gnome-tweak-tool
  - golang
  - hunspell-fr
  - htop
  - ipcalc
  - iptraf
  - jq
  - keepassxc
  - libnss3-tools
  - libreoffice-calc
  - libreoffice-writer
  - lsb-release
  - lsof
  - nautilus-nextcloud
  - net-tools
  - nethogs
  - netcat
  - nextcloud-desktop
  - numix-gtk-theme
  - numix-icon-theme
  - pepperflashplugin-nonfree
  - python3-docker
  - python3-pip
  - rhythmbox
  - rsync
  - shellcheck
  - siege
  - simple-scan
  - strace
  - subversion
  - tcpdump
  - telnet
  - tig
  - traceroute
  - tree
  - vlc
  - wget
  - whois
  - xmlstarlet
