---

binaries:
  docker-compose: "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-Linux-x86_64"
  hadolint: "https://github.com/hadolint/hadolint/releases/download/v1.17.3/hadolint-Linux-x86_64"
  jl: "https://github.com/koenbollen/jl/releases/download/v1.2.0/jl_linux_amd64"
  stern: "https://github.com/wercker/stern/releases/download/1.11.0/stern_linux_amd64"
  gitlab-runner: "https://gitlab-runner-downloads.s3.amazonaws.com/v12.7.1/binaries/gitlab-runner-linux-amd64"

helm_version: v3.0.2
terraform_version: 0.12.18
packer_version: 1.5.5
dive_version: 0.9.1
tflint_version: 0.13.4
starship_version: 0.38.0

gems:
  rake: "12.3.3"
  serverspec: "2.41.3"

google_cloud_sdk_version: "286.0.0-0"
kubectl_version: "1.17.4-00"

pip_packages:
  - molecule==3.0.2
  - pre-commit==2.1.1
  - docker==4.2.0

packages:
  - ack
  - aspell-en
  - aspell-fr
  - bash-completion
  - build-essential
  - ccze
  - cups
  - curl
  - dnsutils
  - evince
  - file-roller
  - filezilla
  - firmware-linux
  - firmware-linux-free
  - firmware-linux-nonfree
  - gdm3
  - gnome-core
  - gnome-shell
  - gnome-tweak-tool
  - golang
  - htop
  - iptraf
  - jq
  - keepassx
  - libreoffice-calc
  - libreoffice-writer
  - lsb-release
  - lsof
  - net-tools
  - netcat
  - nextcloud-desktop
  - numix-gtk-theme
  - numix-icon-theme
  - pepperflashplugin-nonfree
  - python-docker
  - python3-pip
  - rhythmbox
  - rsync
  - shellcheck
  - siege
  - simple-scan
  - strace
  - subversion
  - tcpdump
  - telnet
  - tig
  - traceroute
  - tree
  - vlc
  - wget
  - whois
