---
- name: Let me use Control+Shift+E key in terminator please !
  command: gsettings set org.freedesktop.ibus.panel.emoji hotkey "['<Control><Shift>j']"
  changed_when: false

- name: Configure nautilus bookmarks (global)
  become: true
  template:
    src: etc/xdg/user-dirs.defaults.j2
    dest: /etc/xdg/user-dirs.defaults
    mode: 0644
    owner: root
    group: root

- name: Configure nautilus bookmarks (user)
  template:
    src: .config/user-dirs.dirs.j2
    dest: ~/.config/user-dirs.dirs
    mode: 0644

- name: Configure NetworkManager to handle ethernet card
  become: true
  replace:
    path: /etc/NetworkManager/NetworkManager.conf
    regexp: '^\[ifupdown\]\nmanaged=[a-z]*$'
    replace: '[ifupdown]\nmanaged=true'
  notify:
    - NetworkManager restart
