---

- name: Install useful binaries
  become: true
  get_url:
    url: "{{ item.value }}"
    dest: "/usr/local/bin/{{ item.key }}"
    mode: 0755
    owner: root
    group: root
  with_dict: "{{ binaries }}"

- name: Install useful gems
  gem:
    name: "{{ item.key }}"
    version: "{{ item.value }}"
    state: present
  with_dict: "{{ gems }}"

- name: Create ~/.bashrc.d directory
  file:
    path: ~/.bashrc.d
    state: directory

- name: Source all files in ~/.bashrc.d directory
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: EOF
    block: |
      for file in ~/.bashrc.d/*; do
        if [ -r $file ]; then
          . $file
        fi
      done
