---
- name: Configure /etc/apt/preferences
  become: true
  template:
    src: etc/apt/preferences.j2
    dest: /etc/apt/preferences
    mode: 0644
    owner: root
    group: root
  notify:
    - apt update

- name: Configure /etc/apt/sources.list
  become: true
  template:
    src: etc/apt/sources.list.j2
    dest: /etc/apt/sources.list
    mode: 0644
    owner: root
    group: root
  notify:
    - apt update

- name: Remove useless packages
  become: true
  apt:
    name: firefox-esr
    state: absent

- name: Inject packages list in ansible_facts
  package_facts:
    manager: "auto"

- name: Install firefox from unstable repository
  become: true
  apt:
    name: firefox
    state: present
    update_cache: true
    default_release: unstable
  when: '"firefox" not in ansible_facts.packages'
  register: firefox_installed
  until: firefox_installed is success
  retries: 10
  delay: 2

- name: Install useful packages
  become: true
  apt:
    name: "{{ useful_packages }}"
    state: present
    update_cache: true
  register: packages_installed
  until: packages_installed is success
  retries: 10
  delay: 2

- name: Check binaries versions
  shell: >
    set -o pipefail;
    /usr/local/bin/{{ item.value.check }} | head -n 1
  args:
    executable: /usr/bin/bash
  failed_when: false
  changed_when: false
  register: current_binaries_versions
  loop: "{{ binaries | dict2items }}"

- name: Download binaries if needed
  become: true
  get_url:
    url: "{{ item.item.value.url }}"
    dest: "/usr/local/bin/{{ item.item.value.name }}"
    force: true
    mode: 0755
    owner: root
    group: root
  loop: "{{ current_binaries_versions.results }}"
  when: item.stdout is not search(item.item.value.version)

- name: Check archived binaries versions
  shell: >
    set -o pipefail;
    /usr/local/bin/{{ item.value.check }} | head -n 1
  args:
    executable: /usr/bin/bash
  failed_when: false
  changed_when: false
  register: current_archived_binaries_versions
  loop: "{{ archived_binaries | dict2items }}"

- name: Download archived binaries if needed
  become: true
  unarchive:
    src: "{{ item.item.value.url }}"
    dest: /usr/local/bin
    remote_src: true
    mode: 0755
    owner: root
    group: root
  loop: "{{ current_archived_binaries_versions.results }}"
  when: item.stdout is not search(item.item.value.version)

- name: Create starship config
  template:
    src: .config/starship.toml.j2
    dest: ~/.config/starship.toml
    mode: 0644

- name: Install useful gems
  gem:
    name: "{{ item.key }}"
    version: "{{ item.value }}"
    state: present
  with_dict: "{{ gems }}"

- name: Create global git config
  template:
    src: .gitconfig.j2
    dest: ~/.gitconfig
    mode: 0644

- name: Create golang directory
  file:
    path: "~/go"
    state: directory
    mode: 0755

- name: Add gcloud sdk apt-key
  become: true
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  register: gcloud_key_installed
  until: gcloud_key_installed is success
  retries: 10
  delay: 2

- name: Add gcloud sdk repository
  become: true
  apt_repository:
    repo: "deb http://packages.cloud.google.com/apt cloud-sdk-buster main"
    state: present
    filename: google-cloud-sdk
    update_cache: true

- name: Install gcloud sdk
  become: true
  apt:
    name: google-cloud-sdk={{ google_cloud_sdk_version }}
    state: present
    update_cache: true
  register: gcloud_installed
  until: gcloud_installed is success
  retries: 10
  delay: 2

- name: Install evil chrome
  become: true
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  register: chrome_installed
  until: chrome_installed is success
  retries: 10
  delay: 2
  when: '"google-chrome-stable" not in ansible_facts.packages'

- name: Add spotify apt-key
  become: true
  apt_key:
    url: https://download.spotify.com/debian/pubkey.gpg
    state: present
  register: spotify_key_installed
  until: spotify_key_installed is success
  retries: 10
  delay: 2

- name: Add spotify repository
  become: true
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    state: present
    filename: spotify
    update_cache: true

- name: Install spotify
  become: true
  apt:
    name: spotify-client
    state: present
    update_cache: true
  when: '"spotify-client" not in ansible_facts.packages'
  register: spotify_installed
  until: spotify_installed is success
  retries: 10
  delay: 2

- name: Add docker apt-key
  become: true
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  register: docker_key_installed
  until: docker_key_installed is success
  retries: 10
  delay: 2

- name: Add docker repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
    state: present
    filename: docker
    update_cache: true

- name: Install docker
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
  when: '"docker-ce" not in ansible_facts.packages'
  register: docker_installed
  until: docker_installed is success
  retries: 10
  delay: 2

- name: Add {{ lookup('env','USER') }} to group docker
  become: true
  user:
    name: "{{ lookup('env','USER') }}"
    groups: docker
    append: true

- name: Download docker-compose autocomplete file
  become: true
  get_url:
    url: "https://raw.githubusercontent.com/docker/compose/{{ binaries.docker_compose.version }}/contrib/completion/bash/docker-compose"
    dest: /etc/bash_completion.d/docker-compose
    mode: 0644
    owner: root
    group: root

- name: Configure ssh client
  template:
    src: .ssh/config.j2
    dest: ~/.ssh/config
    mode: 0600

- name: Install pip packages
  pip:
    name: "{{ pip_packages }}"
    executable: /usr/bin/pip3

- name: Create ~/.yamllint.yml configuration file
  template:
    src: .yamllint.yml.j2
    dest: ~/.yamllint.yml

- name: Setup splash screen
  become: true
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT=.*"
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"'
  notify:
    - update-grub

- name: Add nodesource apt-key
  become: true
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add nodesource repository
  become: true
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} buster main"
    state: present
    filename: nodejs
    update_cache: true

- name: Install nodejs
  become: true
  apt:
    name: "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
    state: present

- name: Install global nodejs packages
  become: true
  npm:
    name: "{{ item }}"
    global: true
    state: present
  with_items: "{{ nodejs_packages }}"
