---
- name: apt update
  become: true
  apt: update_cache=true

- name: NetworkManager restart
  become: true
  systemd:
    name: NetworkManager
    state: restarted

- name: update-grub
  become: true
  command: /usr/sbin/update-grub

- name: restart bind9
  become: true
  service:
    name: bind9
    state: restarted
