---
- name: update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: restart networkmanager
  become: true
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted

- name: update-grub
  become: true
  ansible.builtin.command: /usr/sbin/update-grub

- name: restart bind9
  become: true
  ansible.builtin.service:
    name: bind9
    state: restarted
