---

- name: apt update
  become: true
  apt: update_cache=true
  register: cache_updated
  until: cache_updated is success
  retries: 10
  delay: 2

- name: NetworkManager restart
  become: true
  systemd:
    name: NetworkManager
    state: restarted

- name: update-grub
  become: true
  command: /usr/sbin/update-grub
