---
- name: Create .vimrc configuration file
  template:
    src: .vimrc.j2
    dest: ~/.vimrc

- name: Remove this shitty mouse support
  become: true
  replace:
    path: /usr/share/vim/vim81/defaults.vim
    regexp: '^  set mouse=a'
    replace: '"  set mouse=a'
  ignore_errors: true

- name: Create ~/.yamllint.yml configuration file
  template:
    src: .yamllint.yml.j2
    dest: ~/.yamllint.yml

- name: Create Vim configuration directory
  file:
    path: "~/.vim"
    state: directory

- name: Create Vundle directory
  file:
    path: "~/.vim/bundle"
    state: directory

- name: Clone Vundle repository
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "~/.vim/bundle/Vundle.vim"
    update: true
    force: true
    version: "{{ vundle_version }}"

- name: Install Vundle plugins
  command: 'vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa'
  changed_when: false
