---
name: CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install dependencies
        run: python -m pip install --upgrade pip virtualenv
      - name: install dependencies
        run: make install-dependencies
      - name: run tests
        run: make tests
